name: frontend CI/CD Pipeline

on:
    workflow_dispatch:
    push:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            ACTIONS_STEP_DEBUG: true # 디버그 모드 활성화

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Build Docker image
              run: |
                  docker build \
                  --build-arg REACT_APP_API_URL=http://${{secrets.GAMEMATE_APP_URL}}:8080 \
                  --build-arg REACT_APP_PYTHON_API_URL=http://${{secrets.GAMEMATE_APP_URL}}:8000 \
                  --build-arg REACT_APP_KAKAOMAP_API_KEY=${{secrets.KAKAOMAP_API_KEY}} \
                  -t gamemate-fe-ik .

            - name: Set up AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Log in to AWS ECR Public
              run: |
                  aws ecr-public get-login-password --region ${{secrets.AWS_REGION}} \
                  | docker login --username AWS --password-stdin public.ecr.aws

            - name: Push Docker image to ECR Public
              run: |
                  docker tag gamemate-fe-ik:latest public.ecr.aws/u8s0u4u6/gamemate-ik/fe:latest
                  docker push public.ecr.aws/u8s0u4u6/gamemate-ik/fe:latest

            - name: Deploy to EC2
              uses: appleboy/ssh-action@v0.1.7
              with:
                  host: ${{ secrets.GAMEMATE_APP_URL }}
                  username: ubuntu
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      sudo docker pull public.ecr.aws/u8s0u4u6/gamemate-ik/fe:latest
                      sudo docker stop gamemate-fe-ik || true
                      sudo docker rm gamemate-fe-ik || true
                      sudo docker run -d --name gamemate-fe-ik --network my_network -p 80:80 public.ecr.aws/u8s0u4u6/gamemate-ik/fe:latest
                  debug: true
